"""empty message

Revision ID: a6e2a53f8246
Revises: 
Create Date: 2019-01-15 00:25:55.813166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e2a53f8246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplied_data',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('original_file', sa.String(length=100), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=True),
    sa.Column('form_name', sa.Enum('upload_form', 'url_form', 'text_form', name='formname'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplied_data')
    # ### end Alembic commands ###
